name: Pylint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.1"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      id: cp310
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pipenv'
    - name: Install dependencies
      run: |        
        python -m pip install --upgrade pip
        pip install pylint
        pip install pipenv
        pipenv  --python '${{ steps.cp310.outputs.python-version }}' install --dev
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint --rcfile=.pylintrc src/*.py

    # - name: Analysing the code with pycodestyle
    #   run: |
    #     pip install pycodestyle
    #     pipenv run  pycodestyle core/views.py core/views_platform.py core/views_classc.py core/views_clickhouse.py core/models.py
    # - name: Analysing the code with black
    #   run: |
    #     pipenv install --skip-lock "black==22.3.0"
    #     pipenv run black --check core/views.py core/views_platform.py
    #     # $(git ls-files '*.py')