name: docker-ci

on:
  push:
    branches:
    - "main"
  pull_request:
    branches: 
    - "main"
    - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - uses: actions/checkout@v2
      - name: Build & Publish the Docker image
        run: |
          docker build . --file Dockerfile --tag gcr.io/covalent-project/bsp-finalizer:latest
          docker push gcr.io/covalent-project/bsp-finalizer:latest;