name: docker-ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - uses: actions/checkout@v2
      - name: Build & Publish the Docker image
        run: |
          docker build . --file Dockerfile --tag us-docker.pkg.dev/covalent-project/network/bsp-finalizer:latest
          docker push us-docker.pkg.dev/covalent-project/network/bsp-finalizer:latest;
