name: hadolint

on:
  push:
    branches:
    - "main"
  pull_request:
    branches: 
    - "main"
    - "develop"

jobs:
  hadolint:
    name: dockerfile-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
